baseURL = "/"
languageCode = "en-us"
title = "A Thoughtful Goose"

theme = "blank"

enableRobotsTXT = true

[blackfriday]
	plainIDAnchors = true
	hrefTargetBlank = true

[params]
	handle = "gooseus"
	author = "Shawn Marincas"
	description = "My personal thoughts on life, the universe, and everything."
	keywords = "philosophy,science,life,the universe,complexity,fragility"

[[menu.main]]
	name = "Thoughts"
	title = "thoughts list"
	weight = -110
	identifier = "thoughts"
	url = "/thoughts/"


