baseURL = "https://goose.us/"
languageCode = "en-us"
title = "A Thoughtful Goose"

theme = "blank"

enableRobotsTXT = true

[taxonomies]
  tag = ""
  group = ""
  category = ""

[blackfriday]
	plainIDAnchors = true
	hrefTargetBlank = true

[params]
	handle = "gooseus"
	author = "Shawn Marincas"
	description = "Thoughts on Life, the Universe, and Everything."

[[menu.main]]
	name = "Thoughts"
	title = "All the Thoughts"
	weight = -110
	identifier = "thoughts"
	url = "/thoughts/"

[Params.fmt]
  ISO8601 = "2006-01-02T15:04:05-07:00"
